- package.json
- src/pages/app-bar/collapsible-app-bar/index.tsx
- src/pages/app-bar/search-bar/index.tsx
- src/pages/lists/multiselect-list/index.tsx
- yarn.lock
Fixes #14.
Changes proposed in this Pull Request:
- Use `<InfoListItem />` for places that needs it
- Double checked and made sure there are no more ListItem needs to be replaced with InfoListItem
> Use infolistitem

- package.json
- yarn.lock
Changes proposed in this Pull Request:
- Removes beta dependencies
- Updates lockfile
> Update beta dependencies

- .circleci/config.yml
- Convert config.yml to use CircleCI workflows
- Separate the circleCI tests into another workflow
- Only run these tests for Dev and Master branches
> Convert to circleCI workflows

- package.json
- src/pages/i18n/Drawer.tsx
- src/pages/i18n/index.tsx
- yarn.lock
Fixes PXBLUE 1533.
- Open drawer from same side as button
- Alphabetize languages in dropdown
- Remove chevron from list items
> i18n updates

- src/pages/lists/responsive-table/index.tsx
- src/pages/lists/sortable-list/index.tsx
Fixes PXBLUE-1535.
- Add instruction to responsive table
- Update drag handle size for sortable list
- Change background color of dragged item in sortable list
> List design pattern updates

- cypress/integration/overlays/complex-bottom-sheet.spec.js
- Fix cytest - Labels needed capitalized
> Fix cytests

- src/pages/app-bar/collapsible-app-bar/index.tsx
- src/pages/app-bar/search-bar/index.tsx
-  Match angular typography and banner height
> Match typography

- src/pages/overlays/complex-bottom-sheet/index.tsx
- Set heroBanner height to 100px (matches angular)
> Add height to heroBanner

- src/pages/lists/action-list/index.tsx
Fixes PXBLUE-1572.
- Update list item text for action list items
> Update list item text for action list items

- src/pages/loading-states/index.tsx
- yarn.lock
Fixes #33 
- Use hooks and states to patch this
> Use hooks and states to decide when to fetch data

- .circleci/config.yml
- cypress/integration/lists/sortable-list.spec.js
- package.json
- yarn.lock
- cytest runs locally no issues, need to verify what CI does now
- wait on server was running on 1.11.14 and we want 1.11.1 for now
- update sortable test to include "ListItemAvator-root" with get action to focus test on entire row with handlebar
> wait on server to use strict version update test

- package.json
- src/index.tsx
- src/pages/i18n/index.tsx
- yarn.lock
- Update to latest theme package
- Update font import syntax
> Update to latest theme and font packages

- package.json
- src/pages/form-validation/index.tsx
Fixes #44 
- Fix the spacing between form elements
- Add precommit script
> Fix forms to match design specs

- package.json
- yarn.lock
looks like the wait-on for testing isn't working out of the box with latest react-scripts. Replace with start-server-and-test
- Remove wait-on package
- Add start-server-and-test to work with latest react-scripts
-
> use start server and test

- cypress/integration/appbar/collapsible-app-bar.spec.js
- comment out cypress collapsible app bar test until #37  is updated
- 
- 
-
> no run for cypress collapsible-app-bar

- cypress/integration/loading-wait-states/contextual-spinners.spec.js
- cypress/integration/loading-wait-states/progress-bars.spec.js
- cypress/integration/loading-wait-states/skeleton-loader.spec.js
- cypress/integration/loading-wait-states/spinner-overlay.spec.js
- cypress/integration/overlays/complex-bottom-sheet.spec.js
- src/pages/loading-waiting-states/contextual-spinner/ContextualSpinner.tsx
- src/pages/loading-waiting-states/progress-bar/index.tsx
- src/pages/loading-waiting-states/skeletons/components/ScorecardPlaceholder.tsx
- src/pages/loading-waiting-states/spinner-overlays/index.tsx
- add tests for contextual-spinners, progress-bars, skeleton-loader and spinner-overlay
- update bottomsheet cypress test to run dismiss bottomsheet first
- 
-
> add cypress tests

- src/pages/form-validation/list/index.tsx
- src/pages/form-validation/list/list-validation.test.tsx
- src/pages/form-validation/password/index.tsx
- src/pages/form-validation/password/password-validation.test.tsx
- src/router/main.tsx
- src/router/routes.tsx
- Add in a list example 
- Add change password example
> In a List & Change Password Example

- src/pages/form-validation/fixed-length-passcode/index.tsx
- use `startIcon` for slightly better styling.
> Use startIcon

- src/pages/app-bar/collapsible/index.tsx
- src/pages/app-bar/utils/utils.tsx
Fixes [81](https://github.com/pxblue/react-design-patterns/issues/81) .
- Show dummy content
-
> add body content

- src/pages/lists/action-list/action-list-button-panel/action-list-button-panel.test.tsx
- src/pages/lists/action-list/action-list-button-panel/index.tsx
- src/router/main.tsx
- src/router/routes.tsx
Fixes PXBLUE-2542.
- Add global action list with button panel example
> Add global action list with button panel example

- cypress/integration/lists/multiselect-list.spec.js
- src/pages/lists/multiselect-list/index.tsx
Fixes Cypress Test for multiselect
> fix cypress test multiselect

- .circleci/config.yml
Fixes # .
- add resource large (this may help out with cy tests race conditions and DOM elements hanging around during tests)
- 
- 
-
> use large resource to see if test pass in ci

- cypress/integration/appbar/contextual-action.spec.js
- Set cypress to use docker large
> Set cypress to use docker large

- src/pages/form-validation/sectioned-form/index.tsx
Fixes #128 
- Added error to form control
- yarn start
- Open Sectioned Form under Forms and Validations
- Click on Submit without filling the State
> 2845 Added error to form control

- .circleci/config.yml
Fixes # .
- bump node image version for cypress
- 
- 
-
> update node image ver for cypress

- .github/workflows/combine-prs.yml
Fixes # .
- add combine PR's workflow to make security patch pull request quicker
- 
- 
-
> add combine pr workflow

- package.json
- src/App.tsx
- src/router/main.tsx
- yarn.lock
Fixes #153 BLUI-3713
- Updated react-router to v6
- Updated react-router-dom to v6
- Updated routes 
- yarn start
> Updated react router, react router dom to v6

- src/pages/dynamic-stepper/index.tsx
Fixes [#23](https://github.com/etn-ccis/blui-react-design-patterns/issues/23)  BLUI-3712
- Added a conditional on click handler in dynamic stepper
https://user-images.githubusercontent.com/25982779/209767812-2a2a515b-4c3e-4dbf-add1-07d6b4fadb77.mov
- yarn start
- Navigate to Dynamic Stepper
- Add step and chose an option
- Click on Step title to open
- Click on the expanded step title to close
> Added conditional on change handler to dynamic stepper

- src/App.tsx
Fixes #105 BLUI-3715
- Added a condition for hidePadding prop in drawer item
- Updated createRoute function
https://user-images.githubusercontent.com/120575281/210214228-422371a5-9330-41f0-9472-1170346d7475.mov
- yarn start
- Open any drawer item which has sub items (e.g. Account Menu)
- See sub items have left side padding
> Added hidePadding prop to drawer nested items

- .github/pr-labeler.yml
- .github/workflows/labeler.yml
- .github/workflows/pr-labeler.yml
- README.md
> Ignore this PR

- .github/pr-labeler.yml
- README.md
> Update read me from testing labels

- .github/workflows/blui-pr-actions.yml
Fixes BLUI-4197.
- use new pr comment
- 
- 
-
- 
-
> Blui 4197 use new comment

- README.md
> Blui 4197 no merge

- .github/workflows/blui-pr-actions.yml
Fixes # .
-  remove pull request target & branches
- 
- 
-
- 
-
> test without on pull request in caller

- .github/workflows/blui-pr-actions.yml
Fixes # .
- match instructions for the caller to match workflow
- 
- 
-
- 
-
> try instructions for caller

- .github/workflows/blui-pr-actions.yml
Fixes # .
- remove the branches input
- 
- 
-
- 
-
> remove branch input

- .github/workflows/blui-pr-actions.yml
Fixes BLUI-4197 .
- remove types & branches from caller and let workflow control it
- 
- 
-
- 
-
> remove types & branches

- .github/workflows/firebase-hosting-pull-request.yml
- update firebase hosting on PR if github.actor != 'dependabot[bot]' 
- this should skip deploy rather than getting a failed response from dependabot pull requests
- 
-
-  need to wait until a new PR from dependabot comes in to verify. In couple weeks. But we can merge this now.
-
> update firebase deploy & skip if dependabot
